Fble Compile(1)
===============

== NAME ==

fble-compile - compile an fble module

== SYNOPSYS ==

*fble-compile* ['OPTION'...] *-m* 'MODULE_PATH'

== DESCRIPTION ==

Compile the fble module identified by 'MODULE_PATH'.

There are three kinds of things that can be included in the generated code:

1. Code generated for executing the given module. This will generate an
FbleCompiledModuleFunction for the module under an internal name that
users should not directly reference.

2. A named *FbleCompiledModuleFunction* function to export the code generated
for a module. Users provide their desired name for this function. The
compiler will re-export the internally named *FbleCompiledModuleFunction* from
(1) under this user specified name.

3. A standard *main* function that invokes a user provided wrapper function.
The wrapper function should have type:
+
*int* 'NAME'**(int argc, const char argv, FbleCompiledModuleFunction* module);**
+
It will be called passing 'argc' and 'argv' from *main* and the compiled
module generated in (1).

== OPTIONS ==
=== Generic Program Information ===
*-h, --help*::
  display this help text and exit
*-v, --version*::
  display version information and exit

=== Input control ===
*-I* 'DIR'::
  add 'DIR' to the module search path
*-m, --module MODULE_PATH*::
  path of the module to compile

=== Target control ===
*-t, --target* [*aarch64* | *c*]::
  what to compile to, defaults to *aarch64*

=== Output control ===
*-c, --compile*::
  generate compiled code for the module
*-e, --export* 'NAME'::
  generate 'NAME' function to export the module
*--main* 'NAME'::
  generate main function using 'NAME' wrapper

At least one of *--compile*, *--export*, or *--main* must be provided.

== EXIT STATUS ==

*0*:: Success
*1*:: Failure
*2*:: Usage Error

== EXAMPLE ==

*fble-compile -c -e CompiledFoo -I foo -m /Foo% > Foo.fble.s*::
  Compiles */Foo%* to an **FbleCompiledModuleFunction*** called *CompiledFoo*.

*fble-compile -c --main FbleStdioMain -I foo -m /Foo% > foo.s*::
  Generates a standalone program that invokes *FbleStdioMain* on the compiled
  code for */Foo%* when run.
