Fable
=====
Richard Uhler <ruhler@degralder.com>

Fable is a programming language project. It includes a specification,
reference implementation, library, and sample applications for the fble
programming language.

== Overview ==

Fable is a hobby project to design my own programming language. My goal is to
design a general purpose programming language good enough to be my preferred
programming language.

== Documentation ==

Fble Language Specification::
* Source: link:spec/fble.adoc[]
* Generated: link:spec/fble.html[]

Tutorials::
* Source: link:tutorials/Tutorials.adoc[]
* Generated: link:tutorials/index.html[]

Fble C API::
* Source: link:include/fble[]
* Doxygen Generated: link:include/index.html[]

Fble Internals::
* Source: link:lib/fble[]
* Doxygen Generated: link:lib/index.html[]

== Directory Structure ==

bin/:: Source code for fble compiler binaries.
book/:: Drafts for a book about the design of the fble language.
fbld/:: A lightweight document markup language used for documenting fble.
include/:: Public header files for the fble library.
lib/:: Source code for an fble interpreter and compiler implemented in C.
pkgs/:: Sample fble library and application packages.
spec/:: Specification of the fble language, including spec tests.
test/::  Source code for fble test binaries and other test utilities.
thoughts/:: A collection of running discussions about fble.
tutorials/:: Fble language tutorials.
vim/:: Vim syntax files for fbld and fble.
www/:: Source for the fble website.

== Build Requirements ==

To build and run the tests for Fable, the following software is required. The
version numbers provided are versions that are known to work:

AsciiDoc 8.6.10:: For documentation.
Doxygen 1.8.13:: For source code documentation.
Expect 5.45.4:: To test fble debugging.
GNU Binutils for Debian 2.31.1:: For assembling compiled fble programs.
GNU Bison 3.3.2:: For generating the fble parser.
GNU Compiler Collection (Debian 8.3.0-6) 8.3.0:: For compiling fble.
GNU Debugger (Debian 8.2.1-2+b3) 8.2.1:: Used to test fble debugging.
GNU diffutils 3.7:: For some test cases.
GNU grep 3.3:: For some test cases.
GNU groff version 1.22.4:: For formatting help usage text.
Ninja 1.10.1:: For the build system.
Open GL 1.2:: For graphical fble apps.
Simple DirectMedia Layer 2.0.9:: For graphical fble apps.
Tcl 8.6:: For generating build ninja files.

To install required dependencies on a debian based system:

  $ apt install \
      asciidoc doxygen expect binutils bison \
      gcc gdb diffutils grep groff-base ninja-build \
      libgl-dev libsdl2-dev tcl8.6

== Build and Test ==

To build:

  $ mkdir build
  $ cd build
  $ ../configure --prefix=/usr/local
  $ ninja

To run tests:

  $ ninja check

To install:

  $ ninja install

== Vim Files ==

Vim ftplugin, syntax, and indent files for the fble language are available in
the `vim/` directory. You can run the following commands to install these files:

  $ mkdir -p ~/.vim/ftdetect ~/.vim/ftplugin ~/.vim/indent ~/.vim/syntax
  $ cp vim/ftdetect/* ~/.vim/ftdetect
  $ cp vim/ftplugin/* ~/.vim/ftplugin
  $ cp vim/indent/* ~/.vim/indent
  $ cp vim/syntax/* ~/.vim/syntax
