Fbld
====
Richard Uhler <ruhler@degralder.com>

== Introduction ==

Fbld is a lightweight markup language for structured text. It aims to balance
the readibilty of markup languages like asciidoc and markdown with the
extensibility and clarity of structure of markup languages like xml.

Note: Fbld should not be confused with the predecessor to fble, which was also
called fbld. We reuse the name `fbld` in this case to suggest the term `Fable
Doc Language`.

=== Goals ===

The primary design goals of fbld are:

* It should be easy to parse, by both human and computer. There should not be
  weird corner cases, ambiguity, or complex resolution rules for parsing like
  there are for markdown, for example.

* The main textural content should be easy to read from source by a human. It
  should not include excessive clutter from tags that overly distract from the
  contents of the text, as is the case with roff and xml, for example.

* It should be easy to provide custom processing of the document. For example,
  conversion to html, latex, roff, or anything you might like.

* It should support custom structure, allowing a user to define their own new
  kinds of structures and use those structures in their documents.

=== Use Cases ===

The original use cases motivating development of the fbld language are:

* Document functions in code and automatically generate man pages from it.

* Document command line usage and automatically generate both man page and
  help usage text from it.

* Mark up README files, tutorials, and language specifications to add clarity
  to structure and make it possible to generate books, webpages, etc. with
  that information.

=== Alternatives ===

There are many alternatives for document markup. Each of the ones I tried had
their own issues. Some of the issues are subtle and quite subjective. Here are
a list of alternatives I considered before deciding to develop my own markup
language.

Markdown::
* Subtleties in how to parse correctly.
* No support for custom structure components.

Asciidoc::
* Complex to parse and provide custom processing of the document.
* Vim syntax highlighting doesn't work well, if at all.
* You have to know what particular symbols mean to understand the structure of
  a document. For example, `......` versus `////////`.

XML::
* Tags clutter the doc too much.

roff::
* Tags clutter the doc too much.

doxygen::
* Not generally extensible to things beyond code documentation.

tcl::
* Too tedious to have nested inlined structure.

== Inline Structure ==

Fbld interprets text as a sequence of commands to execute. The way fbld
converts text into a sequence of commands depends on whether the text is
treated as inline structure or as block structure. This section introduces the
main concepts of fbld from the point of view of parsing inline structure.

For example, consider the following paragraph of text annotated with fbld
inline structure:

....
It's @emph[really] important to check the result of the @code[malloc] function
in C, in case it returns @NULL. See
@link[the malloc man page][https://manpages.org/malloc] for more details.
....

Explicit commands are introduced with the `'@'` character. In this example
we use commands `@emph`, `@code`, `@NULL`, and `@link`. The meaning of these
commands is entirely user defined. There are no commands built in to fbld.

Arguments to commands are passed within square brackets. For example, `really`
is an argument passed to the `@emph` command, `malloc` is the argument passed
to the `@code` command. The `@NULL` command is given no arguments and the
`@link` command is given two arguments.

Any text not explicitly part of a command or its arguments is grouped together
into a single argument and passed to an implicit default inline command. For
example, let's say the default command was called `@default`. The first,
implicit command from the above text is then `@default[It's ]`.

In summary, the above text is parsed into the following sequence of nine
commands, using tcl syntax for clarity:

[source,tcl]
----
default "It's "
emph "really"
default " important to check the result of the "
code "malloc"
default " function\nin C, in case it returns "
NULL
default ". See\n"
link "the malloc man page" "https://manpages.org/malloc" 
default " for more details."
----

And that's it. The core of how fbld works. Once in the form of a sequence of
commands, users can provide whatever implementation they like for the commands
to process the structure of the document the way they desire.

=== Lexical Details ===

When parsing inline structure, all whitespace is preserved.

Command names are a sequence of one or more alphanumeric or underscore
characters. No other characters are allowed in command names.

The following are special characters in fbld:

* `@`, `[`, `]`, `\`

To use these characters without special processing, prefix them with a
backslash character. For example:

....
My email is ruhler\@degralder.com \[I think\].
....

Would be converted into the single command:

[source,tcl]
----
default {My email is ruhler\@degralder.com \[I think\].}
----

It is illegal to specify `@` without a valid command name immediately
following. It is illegal to use `[` or `]` outside of specifying arguments,
and braces must be properly closed.

The fbld parser has no knowledge of how many arguments a command expects. It
is up to the command to report any misuse in the number of arguments when it
is executed. It is possible for multiple invocations of the same command to be
supplied a different number of arguments.

=== Nested Commands ===

It is possible to use inline structure in arguments to commands. For example:

....
Go @link[@bold[here]][www.degralder.com] for cool stuff.
....

When parsing the first argument to the `@link` command, the text from opening
`[` to matching `]` is used. This is just like how braces work in tcl. In this
case, the sequence of commands would be:

[source,tcl]
----
default "Go "
link "@bold[here]" "www.degralder.com"
default " for cool stuff."
----

It's up to the `@link` command to parse its first argument as inline
structured text if it so desires.

== Block Structure ==

Fbld parses block structured text into a sequence of commands using the same
concepts as inline structure, with a few syntactic differences.

The key idea behind block structure is that blocks of text tend to take a lot
of vertical space, so we can use a little extra vertical space to make the
syntax of passing the last command argument less cluttered.

For example, consider a command, `@block` that takes two arguments: a title
for the block and text to use in the block. We'll always use `[` and `]`
notation to supply the first argument, but there are three different ways we
can supply the last argument.

The first approach is to use a single line for the last argument. To do this,
start the text of the last argument on the same line as the command:

....
@block["Example 1"] This is the first example.
@block["Example 2"] This is the second example.
....

The second approach is to start the last argument on the next line. In this
case, everything up to the next blank line is used for the last argument:

....
@block["Example 1"]
This is the first example.

@block["Example 2"]
This is the second example.
....

The third approach is to use square braces for the last argument, in which
case the command must be followed by a blank line:

....
@block["Example 1"][This is the first example.]

@block["Example 2"][This is the second example.]
....

Typically you would use the same-line last argument for short text, such as
section titles or small list items. You would use the next-line last argument
when the argument is a single paragraph. You would use square braces for the
last argument if it needs to span multiple paragraphs.

=== A Bigger Example ===

Here's an example demonstrating use of the various approaches to the last
argument:

....
@title A Bigger Example

Some introductory text here.

@section[First Section]
[
@paragraph
Here is a paragraph in the first
section of the doc.

@list
@item First item of a list.
@item Second item of a list.
]
....

This would be parsed into the following sequence of three commands:

[source,tcl]
----
title "A Bigger Example"
default "Some introductory text here."
section "First Section" {
@paragraph
Here is a paragraph in the first
section of the doc.

@list
@item First item of a list.
@item Second item of a list.
}
----

The second argument to the `@section` command can then be parsed into its own
sequence of commands:

[source,tcl]
----
paragraph "Here is a paragraph in the first\nsection of the doc."
list "@item First item of a list.\n@item Second item of a list."
----

And the argument to the `@list` command can be parsed into its own sequence:

[source,tcl]
----
item "First item of a list."
item "Second item of a list."
----

=== Lexical Details ===

Whitespace is treated differently for block structured text than it is for
inline structured test. In particular:

* A blank line is a line with a single newline character. It's not considered
  a blank line if there are other whitespace characters in the line.
* Blank lines between blocks are treated as delimiters and otherwise ignored.
* Block commands must start on the first character of a line. They cannot be
  indented.
* Spaces and tabs are allowed between ']' closing an argument and '[' starting
  the next argument.
* Spaces and tabs between ']' and the start of a same-line last argument is
  treated as a delimiter and otherwise ignored.
* A `[` can be used in for an argument starting on the next line. In this case
  the newline between the command or previous arguments `]` is allowed and
  ignored. The `[` must be on column 0 of the next line in this case.

=== Escaping Inline Commands ===

Imagine you want to emphasize the first word of a paragraph:

....
@section A Sample Section

@emph[Yes!] The first word is emphasized
....

In this case, the intention was to use `@emph` as an inline structure command,
but it will end up being parsed as a block structure command:

[source,tcl]
----
section "A Sample Section"
emph "Yes!" "The first word is emphasized"
----

To work around this, you can explicitly pass the paragraph as an argument
that's expected to be inlined structured text. For example:

....
@section A Sample Section

@default
@emph[Yes!] The first word is emphasized
....

Which will be parsed as desired:

[source,tcl]
----
section "A Sample Section"
default "@emph[Yes!] The first word is emphasized"
----

== Handling of Escape Characters ==

The characters `@`, `[`, `]`, and `\` are special and need to be escaped using
`\` to avoid being processed specially. At the end of the day, users will need
to manually remove the escapes.

For example, imagine we want to put an email address in a document that we
convert to markdown:

....
@block[Example]
My email address is @bold[ruhler\@degralder.com].
....

This gets parsed via block structured text as:

[source,tcl]
----
block "Example" {My email address is @bold[ruhler\@degralder.com].}
----

The second argument gets parsed as inline structured text as:

[source,tcl]
----
default "My email address is "
bold {ruhler\@degralder.com}
default "."
----

To actually display the text, the `@bold` command should remove the backslash
before rendering the text.

== TODO ==

* Is the following valid? `hello ] [ @there.` The square brackets are supposed
  to be special, but it's not within a command, so there shouldn't be any need
  to escape them, right? Only need to escape square brackets when parsing
  arguments? This would be a problem if it was within an argument. Maybe best
  to require escaping in all cases for consistency.

* The trailing newline is included in args that go to blank line. The blank
  line is not included.

* Should we allow block commands to be indented?

* Is the newline included in the arg for a same line arg? I feel like it
  shouldn't be?

* Clarify behavior of end of input for block commands, after ].
