
# Test that we can do gdb based debugging of the fble-debug-test binary.

proc require { str } {
  expect {
    $str {}
    timeout {error "timeout waiting for \"$str\"" }
    eof {error "eof waiting for \"$str\"" }
  }
}

eval {
  # Test that we can set a breakpoint at a particular line in a file and run to
  # that breakpoint.
  spawn gdb --quiet ./out/fble/test/fble-debug-test
  expect "(gdb) "

  set STMT_LINE 14
  send "break fble/test/DebugTest.fble:$STMT_LINE\n"
  require "Breakpoint 1 at"
  require "fble/test/DebugTest.fble, line $STMT_LINE."
  require "(gdb) "

  send "run\n"
  require "at fble/test/DebugTest.fble:$STMT_LINE"
  require "(gdb) "
  close
}

eval {
  # Test that we can set a breakpoint at a particular function and run to
  # that breakpoint.
  spawn gdb --quiet ./out/fble/test/fble-debug-test
  expect "(gdb) "

  set LINE 14
  send "break /DebugTest%.Next!\n"
  require "Breakpoint 1 at"
  require "fble/test/DebugTest.fble, line $LINE."
  require "(gdb) "

  send "run\n"
  require "at fble/test/DebugTest.fble:$LINE"
  require "(gdb) "
  close
}

eval {
  # Test that we can print values of local variables
  spawn gdb --quiet ./out/fble/test/fble-debug-test
  expect "(gdb) "

  set LINE 15
  send "break fble/test/DebugTest.fble:$LINE\n"
  require "Breakpoint 1 at"
  require "fble/test/DebugTest.fble, line $LINE."
  require "(gdb) "

  send "run\n"
  require "at fble/test/DebugTest.fble:$LINE"
  require "(gdb) "

  send "info locals\n"
  require "light"
  require "u"
  require "(gdb)"

  # Test that it show the type of the variable as FbleValue*.
  send "print light\n"
  require "(struct FbleValue *)"
  require "(gdb)"

  close
}

exit 0
