
# Test that we can do gdb based debugging of the fble-debug-test binary.

spawn gdb --quiet ./out/bin/fble-debug-test

proc require { str } {
  expect {
    $str {}
    timeout {error "timeout waiting for \"$str\"" }
    eof {error "eof waiting for \"$str\"" }
  }
}

expect "(gdb) "

# Test that we can set a breakpoint at a particular line in a file and run to
# that breakpoint.
set STMT_LINE 31
send "break prgms/Fble/DebugTest.fble:$STMT_LINE\n"
require "Breakpoint 1 at"
require "prgms/Fble/DebugTest.fble, line $STMT_LINE."
require "(gdb) "

send "run\n"
require "at prgms/Fble/DebugTest.fble:$STMT_LINE"
require "(gdb) "

exit 0
