name: build
run-name: ${{github.actor}} Fble Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Env Setup
        run: |
          sudo apt update
          sudo apt install \
            asciidoc doxygen expect binutils bison \
            gcc gdb diffutils grep groff-base ninja-build \
            libgl-dev libsdl2-dev tcl8.6

      - name: Build
        run: |
          mkdir build
          cd build
          ../configure --prefix=${{github.workspace}}/install
          ninja check
          ninja install
