name: build
run-name: Fble Build
on:
  push:
    branches:
      - main
jobs:
  www:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Env Setup
        run: |
          sudo apt update
          sudo apt install \
            expect binutils bison coreutils \
            gcc gdb diffutils grep groff-base \
            ninja-build libgl-dev libsdl2-dev tcl8.6

      - name: Build WWW
        run: |
          ./configure --prefix=${{github.workspace}}/install
          ninja www

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{github.workspace}}/out/www/
          retention-days: 0

  deploy:
    needs: www
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy GitHub Pages site
        id: deployment
        uses: actions/deploy-pages@v4

  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Env Setup
        run: |
          sudo apt update
          sudo apt install \
            expect binutils bison coreutils \
            gcc gdb diffutils grep groff-base \
            ninja-build libgl-dev libsdl2-dev tcl8.6

      - name: Build and Test
        run: |
          ./configure --prefix=${{github.workspace}}/install
          ninja check
          ninja install

  msys2-ucrt64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            tcl ninja gcc bison groff diffutils
            mingw-w64-ucrt-x86_64-toolchain
            mingw-w64-ucrt-x86_64-SDL2
            mingw-w64-ucrt-x86_64-mesa

      - name: Build and Test
        run: |
          export MSYS2_ARG_CONV_EXCL='*'
          ./configure
          ninja check
