name: build
run-name: Fble Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Env Setup
        run: |
          sudo apt update
          sudo apt install \
            expect binutils bison \
            gcc gdb diffutils grep groff-base source-highlight \
            ninja-build libgl-dev libsdl2-dev tcl8.6

      - name: Build and Test
        run: |
          mkdir build
          cd build
          ../configure --prefix=${{github.workspace}}/install
          ninja check
          ninja install

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.7
        with:
          path: ${{github.workspace}}/build/www/

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy GitHub Pages site
        id: deployment
        uses: actions/deploy-pages@v1.2.3
